---
driver:
  name: vagrant
  vm_hostname: logstash-example1.jeeatwork.com
  customize:
    memory: 2048
    cpus: 4
  network:
  - ["forwarded_port", {guest: 9200, host: 9200}]
  - ["forwarded_port", {guest: 5601, host: 5601}]
  - ["forwarded_port", {guest: 80, host: 8888}]
  - ["forwarded_port", {guest: 8889, host: 8889}]

driver_config:
  http_proxy:  <%= ENV['http_proxy'] %>
  https_proxy:  <%= ENV['https_proxy'] %>
  no_proxy:  "<%= ENV['no_proxy'] %>,logstash-example1.jeeatwork.com"

provisioner:
  name: chef_solo
  solo_rb:
    http_proxy:  <%= ENV['http_proxy'] %>
    https_proxy:  <%= ENV['https_proxy'] %>
    no_proxy:  "<%= ENV['no_proxy'] %>,logstash-example1.jeeatwork.com"
  client_rb:
    http_proxy:  <%= ENV['http_proxy'] %>
    https_proxy:  <%= ENV['https_proxy'] %>
    no_proxy:  "<%= ENV['no_proxy'] %>,logstash-example1.jeeatwork.com"

platforms:
- name: centos-6.4

suites:
  - name: default
    run_list:
    - recipe[logstash-example1::default]
    attributes:
      logstash-example1:
        all_proxy:  <%= ENV['all_proxy'] %>
        ftp_proxy:  <%= ENV['http_proxy'] %>
        http_proxy:  <%= ENV['http_proxy'] %>
        https_proxy:  <%= ENV['https_proxy'] %>
        no_proxy:  "<%= ENV['no_proxy'] %>,logstash-example1,logstash-example1.jeeatwork.com"
      tomcat:
        base_version: '7'
        port: 8889