source "https://supermarket.chef.io"

metadata

cookbook 'magic_shell', '~> 1.0.0'
cookbook 'yum', '~> 3.5.3'
cookbook 'java', '~> 1.31.0'
cookbook 'httpd', git: 'https://github.com/chef-cookbooks/httpd.git'
